#!/bin/bash
SECONDS=0 
N=0
for folder in */; do
  let "N++"
done

counter=1

for folder in */; do
  cd $folder
  echo -ne "($counter/$N) pulling from $folder ..."
  let "counter++"
  git co master
  git pull > /dev/null
  cd ..
done

echo "Time cost: $SECONDS s"
