#!/bin/bash
# auto committing all leet files.

git add .
echo "*****  All files loaded *****"
git status
echo "*****  change log *****"
now=$(date + "%T")
git commit -m "auto commit : $now"
echo "* uploading ...  *"
git push
echo "DONE !"
