#!/bin/bash
# auto committing all leet files.

git add .
echo "*****  All files loaded *****"
git status
echo "*****  change log *****"
git commit -m date
echo "* uploading ...  *"
git push
echo "DONE !"
