#!/bin/bash

git add .
echo "--------------------    All files loaded ----- ----- ----- ----- "
git status
echo "----- ----- ----- -----   change log ----- ----- ----- ----- ----- "
now="$(date)"
git commit -m "$now"
echo "* uploading ... *"
git push
echo " Done. "
